% Auto-generated by stereoCalibrator app on 31-Oct-2023
%-------------------------------------------------------

close all


% Define images to process
imageFileNames1 = {'/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left01.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left02.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left03.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left04.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left05.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left06.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left07.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left08.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left09.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Left/left10.png',...
    };
imageFileNames2 = {'/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right01.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right02.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right03.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right04.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right05.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right06.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right07.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right08.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right09.png',...
    '/Users/alberto/computer-science/dim/labs/lab-03/stereo-images/Right/right10.png',...
    };

% Detect calibration pattern in images
detector = vision.calibration.stereo.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames1, imageFileNames2);

% Generate world coordinates for the planar patten keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Read one of the images from the first stereo pair
I1 = imread(imageFileNames1{1});
[mrows, ncols, ~] = size(I1);

% Calibrate the camera
[stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
% h1=figure; showReprojectionErrors(stereoParams);

% Visualize pattern locations
% h2=figure; showExtrinsics(stereoParams, 'CameraCentric');

% Display parameter estimation errors
% displayErrors(estimationErrors, stereoParams);

I2 = imread(imageFileNames2{1});
[rectL, rectR] = rectifyStereoImages(I1, I2, stereoParams);

disparityRange = [0 64];
disparityMap = disparity(rectL, rectR, 'disparityRange', disparityRange);

%%%%%%%%%View the disparity map%%%%%%%%%%%
figure;
imshow(disparityMap, disparityRange);
title('Disparity Map');
colormap('jet');
colorbar;

%%%%%%%%% Reconstruct Point Cloud%%%%%%%%%
ptcloud = reconstructScene(disparityMap, stereoParams) / 1000;

%%% Limit the range of Z and X for display
PC = thresholdPC(ptcloud, [-0.6 0.3; -0.4 0.25; 0 0.95]);

%%%%%%%View point cloud%%%%%%%%%%%%%%%%%%%
figure;
pcshow(PC, rectL);
title('3D Point Cloud');
