#!/bin/bash
set -e
cd "$(dirname "$BASH_SOURCE")"

cookie=$(cat cookie)
course_link='https://stem.elearning.unipd.it/course/view.php?id=6989'
file_link_regex='https://stem.elearning.unipd.it/mod/resource/view.php?id=[0-9]*'
links=$(curl -s $course_link --cookie "$cookie" | grep -o $file_link_regex)

i=1
for link in $links; do
    redirect=$(curl -s $link --cookie "$cookie" | grep -o 'https.*\.pdf') ||
        continue
    file=lecture-$(printf %02d $i).pdf

    echo Downloading $file
    curl -s --cookie "$cookie" $redirect -o $file

    let i++
done
